### PR TITLE
ensure proper XY coordinate generation from key for contact code

### PR DESCRIPTION
**Pull request by bgits**

### CODE REVIEW

**Comment by jeluard** [comment]
@bgits Can you provide more details about what the issue was and how it's fixed?

**Comment by jeluard** [comment]
Not clear what it's solving but will trust you!

**Comment by rachelhamlin** [comment]
Did we deploy this fix to IPFS @bgits?

**Comment by bgits** [comment]
yes

**Comment by rachelhamlin** [comment]
And was the ENS resolver updated by @3esmit?

**Comment by corpetty** [comment]
the second parameter specifies required length, correct?

**Comment by rachelhamlin** [comment]
Following up on this one. @3esmit @bgits is this version of the DApp (all contact codes can be edited) the one we resolve to via ENS? Unfortunately can't manually test myself as the issue was not affecting me.

**Pull request merged**
